//! tokens.rs — GENERATED by blobin-gen from tokens.json (tokens v0.14.0).
//! DO NOT EDIT BY HAND. Regenerate:
//!   blobin-gen tokens.json --rust src/tokens.rs
//!
//! Closes the v1→v3.1 drift (plan §7): the Motion Spec board and this module
//! read the same tokens.json, so a duration in the spec table is the same
//! const the solver executes.

/// A named duration in milliseconds (MDUR.* in the spec).
#[derive(Clone, Copy, Debug)]
pub struct Dur(pub f32);

impl Dur {
    #[inline]
    pub const fn secs(self) -> f32 {
        self.0 / 1000.0
    }
}

/// Spec MDUR scale. Names match the Motion Spec tables verbatim.
pub mod mdur {
    use super::Dur;
    pub const INSTANT: Dur = Dur(90.0);
    pub const QUICK: Dur = Dur(160.0);
    pub const BASE: Dur = Dur(240.0);
    pub const CALM: Dur = Dur(380.0);
    pub const SLOW: Dur = Dur(560.0);
    pub const BREATHE: Dur = Dur(4200.0);
}

/// A cubic-Bézier easing, MEASE.* in the spec.
#[derive(Clone, Copy, Debug)]
pub struct Ease {
    pub p1x: f32,
    pub p1y: f32,
    pub p2x: f32,
    pub p2y: f32,
}

pub mod mease {
    use super::Ease;
    pub const ENTER: Ease = Ease { p1x: 0.2, p1y: 0.8, p2x: 0.2, p2y: 1.0 };
    pub const EXIT: Ease = Ease { p1x: 0.4, p1y: 0.0, p2x: 1.0, p2y: 1.0 };
    pub const INOUT: Ease = Ease { p1x: 0.45, p1y: 0.05, p2x: 0.55, p2y: 0.95 };
    pub const BLOOM: Ease = Ease { p1x: 0.34, p1y: 1.56, p2x: 0.64, p2y: 1.0 };
}

/// Spring presets (mass-spring-damper).
#[derive(Clone, Copy, Debug)]
pub struct SpringToken {
    pub stiffness: f32,
    pub damping: f32,
    pub mass: f32,
}

pub mod mspring {
    use super::SpringToken;
    pub const SETTLE: SpringToken = SpringToken { stiffness: 170.0, damping: 22.0, mass: 1.0 };
    pub const SNAP: SpringToken = SpringToken { stiffness: 260.0, damping: 24.0, mass: 1.0 };
    pub const WOBBLY: SpringToken = SpringToken { stiffness: 200.0, damping: 12.0, mass: 1.0 };
}
