// blobin_item.h — the QQuickItem shim.
//
// This is the ONLY hot C++ on the blob.in path. It owns a Rust engine handle,
// drives it from a frame clock, and in updatePaintNode() copies the Rust mesh
// into a QSGGeometryNode. It contains no shape or animation logic — every
// decision is in blobin-core. Keep it lean (plan §6: shim < 300 LoC total).

#pragma once

#include <QQuickItem>
#include <QElapsedTimer>
#include <rust/cxx.h>
#include "blobin-core/src/ffi.rs.h"   // generated by cxx

class QSGGeometryNode;

namespace blobin {

class BlobInItem : public QQuickItem {
    Q_OBJECT
    QML_ELEMENT
    // Reactive surface. In production these are wired through cxx-qt (Q6
    // hybrid: cold/reactive side). Here we expose them as plain Qt properties
    // bound to the tweaks-panel; the setter forwards into the Rust engine.
    Q_PROPERTY(State state READ state WRITE setState NOTIFY stateChanged)
    Q_PROPERTY(qreal tolerance READ tolerance WRITE setTolerance NOTIFY toleranceChanged)

public:
    enum class State { Idle, Listening, Transmit, Veille };
    Q_ENUM(State)

    explicit BlobInItem(QQuickItem* parent = nullptr);
    ~BlobInItem() override;

    State state() const { return m_state; }
    void setState(State s);

    qreal tolerance() const { return m_tolerance; }
    void setTolerance(qreal t);

signals:
    void stateChanged();
    void toleranceChanged();

protected:
    QSGNode* updatePaintNode(QSGNode* old, UpdatePaintNodeData*) override;
    void geometryChange(const QRectF& newGeom, const QRectF& oldGeom) override;

private slots:
    void onFrame();   // driven by the window's beforeSynchronizing / a timer

private:
    rust::Box<EngineHandle> m_engine;
    QElapsedTimer m_clock;
    State m_state = State::Idle;
    qreal m_tolerance = 0.02;
    bool m_sizeDirty = true;
};

} // namespace blobin
