//! gnuin-compose-core — scene vocabulary (golden-fixture types)
//!
//! Generated by Central (gnu.in-OS simulator). Source of truth for the
//! token values is `gen/gnu_theme.rs` (compile-time const-fn) + `tokens.json`.
//! The JSON fixtures under `scenes/` deserialize 1:1 into `Scene`.

pub type Argb = u32;

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Rect { pub x: f32, pub y: f32, pub w: f32, pub h: f32 }
impl Rect {
    pub const ZERO: Rect = Rect { x: 0.0, y: 0.0, w: 0.0, h: 0.0 };
    pub fn new(x: f32, y: f32, w: f32, h: f32) -> Self { Self { x, y, w, h } }
}

/// Canonical z-band. `NodeKind::band()` is the single authority — surfaces
/// never negotiate priority per-surface.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Band(pub u16);

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NodeKind {
    Background,
    Wallpaper,
    Window,
    Bar,
    Dock,
    Sidebar,
    ContextMenu,
    Launcher,
    Settings,
    Modal,
    Osd,
    Notification,
    ScreenCorner,
}

impl NodeKind {
    /// Non-interactive backings are dropped from the hit / input_region so they
    /// can never absorb a click (the click-absorption fix).
    pub fn is_interactive(self) -> bool {
        matches!(
            self,
            NodeKind::Window
                | NodeKind::Bar
                | NodeKind::Dock
                | NodeKind::Sidebar
                | NodeKind::ContextMenu
                | NodeKind::Launcher
                | NodeKind::Settings
                | NodeKind::Modal
        )
    }

    pub fn band(self) -> Band {
        Band(match self {
            NodeKind::Background => 0,
            NodeKind::Wallpaper => 1,
            NodeKind::Window => 10,
            NodeKind::Bar => 30,
            NodeKind::Dock => 30,
            NodeKind::Sidebar => 60,
            NodeKind::ContextMenu => 100,
            NodeKind::Launcher => 120,
            NodeKind::Settings => 130,
            NodeKind::Modal => 500,
            NodeKind::Osd => 800,
            NodeKind::Notification => 850,
            NodeKind::ScreenCorner => 880,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WallpaperSource { Matugen, Static }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Seed { Orange, Beret, Info, Rust }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Density { Mouse, Touch }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Theme { Dark, Light }

#[derive(Clone, Debug, PartialEq)]
pub enum NodePayload {
    Fill(Argb),
    Wallpaper { generation: u32, source: WallpaperSource },
    Window { app: String },
    Bar { modules: u8 },
    Dock { items: u8 },
    Sidebar { toggles: u8 },
    Menu { rows: u8 },
    Launcher { query: String, items: u8 },
    Settings { seed: Seed, density: Density, theme: Theme },
    Modal { scrim: bool },
    Osd { volume: f32 },
    Notification { stack: u8 },
    ScreenCorner { radius: f32 },
}

/// Spring profiles, resolved from `tokens.json#springs`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Spring { Settle, Snap, Wobbly, None }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TokenBundle { pub radius: f32, pub fill: Argb, pub motion: Spring }

#[derive(Clone, Debug, PartialEq)]
pub struct SceneNode {
    pub id: u32,
    pub kind: NodeKind,
    pub interactive: bool,
    pub layer: Band,
    pub bounds: Rect,
    pub payload: NodePayload,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DamageReason { MotionTick, Generation, Input, Resize }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Damage { pub node: u32, pub rect: Rect, pub reason: DamageReason }

/// `damage(prev, next)` returns only the nodes whose box or payload changed —
/// a motion-only restyle damages just that node, not the screen.
#[derive(Clone, Debug, PartialEq)]
pub struct Scene { pub nodes: Vec<SceneNode>, pub damage: Vec<Damage> }

/// Versioned wire envelope — a superset of the legacy bare `HostMessage`, so
/// surfaces version-negotiate onto one socket.
#[derive(Clone, Debug, PartialEq)]
pub enum Envelope { V1(HostMessage) }

#[derive(Clone, Debug, PartialEq)]
pub enum HostMessage {
    Open { surface: NodeKind, frame: u64 },
    Close { surface: NodeKind, frame: u64 },
    Spawn { app: String, frame: u64 },
    Notify { seq: u32 },
    Settings { seed: Seed, density: Density },
    Damage { node: u32, reason: DamageReason },
    CloseAll,
}
